import {
  BarChart3,
  Bell,
  Banknote,
  Boxes,
  Briefcase,
  BookOpen,
  CalendarDays,
  ClipboardList,
  Contact,
  CreditCard,
  FileText,
  FolderOpen,
  GraduationCap,
  History,
  LayoutDashboard,
  Landmark,
  ListChecks,
  Package,
  Receipt,
  Settings,
  ShieldCheck,
  ShoppingCart,
  TrendingDown,
  TrendingUp,
  Truck,
  Wallet,
  type LucideIcon,
} from 'lucide-react';
import { type NavIconId } from './navigation';

export const navIconRegistry: Record<NavIconId, LucideIcon> = {
  dashboard: LayoutDashboard,
  contacts: Contact,
  vendors: Truck,
  avreichim: BookOpen,
  students: GraduationCap,
  employees: Briefcase,
  income: TrendingUp,
  expenses: TrendingDown,
  invoices: Receipt,
  payments: CreditCard,
  tuition: Wallet,
  clearing: Banknote,
  masav: Landmark,
  procurement: ShoppingCart,
  'purchase-orders': ClipboardList,
  inventory: Boxes,
  assets: Package,
  tasks: ListChecks,
  events: CalendarDays,
  forms: FileText,
  documents: FolderOpen,
  reports: BarChart3,
  notifications: Bell,
  settings: Settings,
  users: ShieldCheck,
  'audit-log': History,
};

export function getNavIcon(icon: NavIconId): LucideIcon {
  return navIconRegistry[icon];
}
